version: '3.9'
services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "192.168.253.129:80:80"
    depends_on:
      - web
    networks:
      - goodyear-net

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.flask
    ports:
      - "192.168.253.129:5000:5000"
    environment:
      - DATABASE_URL=postgresql://vulnuser:vulnpass@db:5432/vulndb
      - REDIS_HOST=redis
      - SECRET_KEY=goodyear-secure-key-2024
    depends_on:
      - db
      - redis
    volumes:
      - ../backend:/app
    networks:
      - goodyear-net
    cap_add:
      - NET_ADMIN
      - NET_RAW

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vulndb
      POSTGRES_USER: vulnuser
      POSTGRES_PASSWORD: vulnpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "192.168.253.129:5432:5432"
    networks:
      - goodyear-net

  redis:
    image: redis:7
    networks:
      - goodyear-net

  nginx:
    image: nginx:alpine
    ports:
      - "192.168.253.129:8080:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - frontend
    networks:
      - goodyear-net

volumes:
  postgres_data:

networks:
  goodyear-net:
    driver: bridge
